version: "3.6"
services:
  api:
    build: .
    container_name: 'api'
    working_dir: /usr/src/api
    ports:
      - ${APP_PORT:-5000}:5000
    volumes:
      - .:/usr/src/api
    environment:
      - ENVIRONMENT=${APP_ENV:-development}
    env_file:
      - .env
