version: "3.6"
services:
  app:
    build: .
    container_name: 'app'
    working_dir: /usr/src/app
    ports:
      - ${APP_PORT:-5000}:5000
    volumes:
      - .:/usr/src/app
    environment:
      - ENVIRONMENT=${APP_ENV:-development}
    env_file:
      - .env
